config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-20 border-t font-medium text-gray-400">
    &copy; Nbnb
</footer>

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated  %}
    <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>    

    {% else %}
    <li class="nav_link"><a href="{% url "users:login" %}">Log in</a></li>
    <li class="nav_link"><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}
</ul>

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <div class="w-full h-64 bg-cover bg-center rounded-xl mb-3" style="background-image: url({{room.first_photo}});"></div>
    <div class="flex justify-between mb-2 truncate">
        <div class="w-4/5 overflow-hidden flex">
            {% if room.host.superhost %}
                <span class="mr-2 uppercase font-medium text-xs border border-black text-black rounded py-1 px-1">superhost</span>
            {% endif %}
            <span class="texm-sm text-gray-600 block truncate">{{room.city}}, {{room.country.name}}</span>
        </div>
        <span class="text-sm flex items-center">
            <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{room.total_rating}}
        </span>
    </div>
    <span class="text-black w-11/12 block truncate">{{room.name}}</span>
</div>

templates/partials/social_login.html
<div>
    <a href={% url 'users:github-login' %}>
        Continue with Github
    </a>
    <a>
        Continue with Kakao
    </a>
</div>